# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vessel/rvTest/rvTest.srcs/sources_1/ip/IROM_1/IROM.xci
# IP: The module: 'IROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vessel/rvTest/rvTest.srcs/sources_1/ip/IROM_1/IROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/vessel/rvTest/rvTest.srcs/sources_1/ip/IROM_1/IROM.xci
# IP: The module: 'IROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vessel/rvTest/rvTest.srcs/sources_1/ip/IROM_1/IROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
