# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vessel/SEU-RISCV-CPU/rvTest/rvTest.srcs/sources_1/ip/PRAM_BRAM/PRAM_BRAM.xci
# IP: The module: 'PRAM_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vessel/SEU-RISCV-CPU/rvTest/rvTest.srcs/sources_1/ip/PRAM_BRAM/PRAM_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PRAM_BRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/vessel/SEU-RISCV-CPU/rvTest/rvTest.srcs/sources_1/ip/PRAM_BRAM/PRAM_BRAM.xci
# IP: The module: 'PRAM_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vessel/SEU-RISCV-CPU/rvTest/rvTest.srcs/sources_1/ip/PRAM_BRAM/PRAM_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PRAM_BRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
