#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Sat Jan 17 15:24:25 CST 2026
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
echo "xvlog --incr --relax -L /opt/Xilinx/Vivado/2017.4/tps/lnx64/gcc-6.2.0/lib64 -prj controller_tb_vlog.prj"
ExecStep xvlog --incr --relax -L /opt/Xilinx/Vivado/2017.4/tps/lnx64/gcc-6.2.0/lib64 -prj controller_tb_vlog.prj 2>&1 | tee compile.log
